config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'aboutpage'=> 'pages#about'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private def comments_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'Hello man, this is our about';
        @content = 'This is the about page';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @allposts = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if (@post.update(post_params));
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    def create
        @post = Post.new(post_params);
        if (@post.save);
            redirect_to @post
        else
            render 'new'
        end
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
  <% @post.comments.each do |comment| %>
    <div class="card bg-light mb-3">
        <div class="card-body">
            <p><strong><%= comment.username %></strong>: <%= comment.body %>
            <%= link_to '[x]', [comment.post, comment],
                                method: :delete,
                                data: {confirm: 'Are you sure?'}%></p>
        </div>
    </div>
  <% end %>

app/views/comments/_form.html.erb
<h5>Add comment-</h5>
<%= form_for([@post, @post.comments.build]) do |f|%>
  <p>
    <%= f.label :username%><br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :body%><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class=>'btn btn-primary'}) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Simpleblog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link"><%= link_to "Home", home_path%></li>
    </ul>
    <li class="nav-item nav-link"><%= link_to "Add", new_post_path%></li>
  </div>
</nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit post- </h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field( :title, {:class=> 'form-control'})%><br>
    </p>
    <p>
    <%= f.label :body %><br>
    <%= f.text_area( :body, {:class=> 'form-control'} )%><br>
    </p>
    <p>
    <%= f.submit(:class=>'btn btn-primary') %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<% @allposts.each do |post| %>
    <div class="card bg-light mb-4">
        <div class="card-body">
        <h2><%= post.title %></h2>
        <p><%= post.body %></p>
        <%= link_to "Read More", post_path(post), :class=>"btn btn-dark" %>
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add new post- </h1>

<%= form_for :post, url: posts_path do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field( :title, {:class=> 'form-control'})%><br>
    </p>
    <p>
    <%= f.label :body %><br>
    <%= f.text_area( :body, {:class=> 'form-control'} )%><br>
    </p>
    <p>
    <%= f.submit(:class=>'btn btn-primary') %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2>
    <%= @post.title %>
</h2>
<p>
    <%= @post.body %>
</p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => "btn btn-dark" %>
<%= link_to "Delete", post_path(@post),
                    method: :delete,
                    data: {confirm: 'Are you sure?'},
                    :class => "btn btn-danger"%>
<hr>

<%= render 'comments/comments' %>
<p></p>
<%= render 'comments/form' %>